import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';
import FuturisticBackground from '@/components/FuturisticBackground';
import Footer from '@/components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative overflow-x-hidden min-h-screen flex flex-col`}
      >
        {/* Animated background blob */}
        <div className="absolute -z-10 w-[60vw] h-[60vw] top-[-20vw] left-[-20vw] bg-blue-600 rounded-full mix-blend-multiply filter blur-3xl opacity-30 animate-blob" />
        <div className="absolute -z-10 w-[60vw] h-[60vw] bottom-[-20vw] right-[-10vw] bg-purple-600 rounded-full mix-blend-multiply filter blur-3xl opacity-30 animate-blob animation-delay-2000" />

        <FuturisticBackground />
        <Navbar />
        <main className="flex-1 px-4 md:px-12 lg:px-24 xl:px-32 max-w-screen-2xl w-full mx-auto pt-12">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
